flake.lock
Nothing special, just bumping versions.
=> flake: 20230408-1

.gitignore, README.md, modules/default.nix, modules/gamescope.nix, modules/linux_hdr.nix, pkgs/gamescope-wrapped/default.nix
- gamescope: add session.{args,env}
- gamescope: fix session reference
- gamescope: drop capSysNice, broken (I will re-add it later)
- git: ignore result-*
=> gamescope: add session.{args,env}; fix session

shared/builder.nix
- Push do cache only late, after all builds end;
- Add some overridable variables for CI behaviors;
- Add success/failures/errors logs;
- Beautier console output;
- Add exit-codes;
- Detect the lack of cachix auth.
=> builder: enhance

flake.lock
Hopefully, the last one without the bot.
=> flake: 20230412-1

flake.lock
Some things need bumping now:
> Dependency DirectX-Headers found: NO found 1.608.2 but need: '>= 1.610.0'
> Dependency wayland-server found: NO found 1.21.0 but need: '>=1.22'
=> Revert "flake-20230414-1: mesa-git, sway-git, wlroots-git"

flake.lock, overlays/default.nix, pkgs/gamescope-git/default.nix, pkgs/input-leap-git/default.nix, pkgs/mesa-git/default.nix, pkgs/wlroots-git/default.nix
- flake: updates nixpkgs, mesa_git, gamescope_git;
- pkgs: add callOverride and adopts it.
=> flake-20230422-1: bump; pkgs: add callOverride

.circleci/config.yml, .github/workflows/needs-cache.yml, .github/workflows/nixpkgs-bump.yml, README.md, shared/builder.nix
=> ci: use circleci, maintain nyxpkgs-unstable branch, major improvements

pkgs/proton-ge-custom/default.nix
- No need to use `overrideAttrs` to change version, just `override`;
- Allow to change the title seen within Steam to be customized.
=> proton-ge-custom: allow some easy overrides

pkgs/linux-cachyos/default.nix
The currently open issue gets fixed by this, so keeping it until we have a solution upstream.
=> linux-cachyos: fix missing features

flake.lock, pkgs/linux-cachyos/default.nix
=> flake-20230504-1: mesa_git, sway_git, wlroots_git, yuzu-ea_git

README.md
JustTNE has previously advised me to do this, but I had to see someone struggling before doing it. Sorry :crying_cat_face:
=> README: separate module from configuration

pkgs/linux-cachyos/default.nix
Attempt to fix #98 
I should have checked evaluation, I didn't and now here we are again.
=> linux_cachyos: fix structuredExtraConfig

README.md, overlays/default.nix, pkgs/openmohaa/default.nix
From release: https://github.com/openmoh/openmohaa/releases/tag/0.50
Note: It does not build with GCC.
=> openmohaa: init

devshells/failures.nix, flake.lock
Daily bump of our `flake.lock`.
Required to update: mangohud, mesa, nixpkgs, wlroots, yuzu-ea
=> flake-20230522-2: mangohud, mesa, nixpkgs, wlroots, yuzu-ea

flake.lock
Daily bump our flakes' inputs.
=> flake-20230524-1: input-leap, mesa, nixpkgs, wlroots, yuzu-ea

pkgs/firedragon/src.json
- Bumped package
- Browsers need updates
- I like chocolate cake
=> firedragon: update 113.0.2

flake.lock
=> flake-20230525-1: mangohud, mesa, nixpkgs, yuzu-ea

devshells/failures.nix, pkgs/libei/default.nix, pkgs/linux-cachyos/versions.nix
=> libei: 1.0.0rc1 -> 1.0.0rc2; linux_cachyos: 6.3.3 -> 6.3.4

flake.lock, overlays/default.nix
Daily bumps with our flakes with a small code enhancement.
=>  flake-20230527-1: gamescope, mesa, wlroots, yuzu 

devshells/failures.nix, flake.lock, pkgs/openmohaa/default.nix
Daily bump to our precious packages.
=> flake-20230531-1 + openmohaa

devshells/failures.nix, flake.lock, pkgs/linux-cachyos/versions.nix
=> flake-20230605-1 + linux_cachyos

flake.lock
Daily bump of our precious packages.
=> flake-20230607-1: gamscope, mesa, sway, wlroots, yuzu-ea

devshells/failures.nix, flake.lock, overlays/default.nix, pkgs/mangohud-git/default.nix
Bump our precious packages again.
=> flake-20230607-2: mangohud, mesa, yuzu-ea

flake.lock
Precious bump to our daily packages.
=> flake-20230608-1: mangohud, mesa, wlroots, yuzu

README.md, flake.lock, flake.nix, overlays/default.nix, pkgs/river-git/default.nix, pkgs/river-git/src.json, pkgs/river-git/update.sh
1. Added a new package;
- (1) This new package is interesting to myself;
=> river: init

flake.lock
Packages bump of our precious daily
=> flake-20230609-1: mesa, sway, yuzu

pkgs/fastfetch/default.nix
Bumped package;
Get the latest and greatest commits;
=> fastfetch: update to unstable-2023-06-10

flake.lock
Daily bump our precious packages :yum:;
Being greedy for always latest and greatest software;
[ ] - Caching
=> flake.lock: bump {mangohud-git,mesa-git,yuzu-git}

devshells/failures.nix, pkgs/linux-cachyos/default.nix, pkgs/linux-cachyos/versions.nix
Latest Linux-cachyOS update;
Get the latest updates;
=> linux-cachyos: update 6.3.7; failures.nix: update

pkgs/firedragon/firedragon.nix, pkgs/firedragon/src.json
Bumped FireDragon to version 114.0.1;
Package updates;
=> firedragon: update 114.0.1

flake.lock
Daily bump of our precious packages.
=> flake-20230615-1: mangohud, mesa, wlroots, yuzu-ea

devshells/failures.nix, pkgs/linux-cachyos/versions.nix
Updated `linux_cachyos`; 
Get the latest version;
=> linux-cachyos: update 6.3.8

flake.lock
Daily dragons and bump dungeons
=> flake-20230616-1: mesa, nixpkgs, wlroots, yuzu-ea

flake.lock, pkgs/yuzu-ea-git/default.nix
Daily bump of our precious packages.
=> flake-20230618-1: gamescope, mesa, sway, wlroots, yuzu-ea

pkgs/openmohaa/default.nix
Bump with no extra magic involved.
=> openmohaa: 0.54.0 -> 0.55.1

flake.lock, pkgs/yuzu-ea-git/default.nix
=> flake-20230620-1: mangohud, mesa, sway, wlroots, yuzu-ea

devshells/failures.nix, flake.lock
=> flake-20230623-1: gamescope, mangohud, mesa, sway, wlroots, yuzu-ea

flake.lock
=> flake-20230625-1: mangohud, mesa, sway, wlroots, yuzu-ea

flake.lock, modules/mesa-git.nix
1. Bump our packages;
2. Add a warning regarding our mesa-git module.
- (1) We bump everyday;
- (2) Let the users be aware of the problems.
=> flake-20230626-1: mangohud, mesa, sway

pkgs/dr460nized-kde-theme/default.nix
Update `dr460nized-kde-theme`
Some nice new theming implemented!
=> dr460nized-kde-theme: update to unstable-2023-06-29

devshells/failures.nix, flake.lock, pkgs/yuzu-ea-git/default.nix
=> bump: 20230630-1

flake.lock
=> flake-20230701-1: mesa, wlroots, yuzu-ea

overlays/default.nix, pkgs/proton-ge-custom/default.nix, pkgs/proton-ge-custom/update.nix, pkgs/proton-ge-custom/versions.json
- Add an update-script to proton-ge-custom;
- Bump proton-ge-custom with said script;
We like our packages auto-updating.
=> proton-ge-custom: add updateScript

flake.lock
=> flake-20230704-1: mesa, yuzu-ea

flake.lock
=> flake-20230705-1: mesa, wlroots, yuzu-ea

devshells/failures.nix, flake.lock, pkgs/linux-cachyos/versions.json
Bump linux_cachyos;
Bump flake-updated packages.
Keep it rolling.
=> linux_cachyos: 6.4.1 -> 6.4.2; flake-20230705-2

flake.lock
=> flake-20230706-1: mesa, yuzu-ea

pkgs/dr460nized-kde-theme/default.nix
Updated a package;
Contains latest changes;
=> dr460nized-kde-theme: update to unstable-2023-07-08

overlays/default.nix, pkgs/beautyline-icons/default.nix, pkgs/blurredwallpaper/default.nix, pkgs/dr460nized-kde-theme/default.nix, pkgs/fastfetch/default.nix
Added a new package;
Needed for current versions of the `dr460nized-kde-theme`;
=> blurredwallpaper: init at v2.2

pkgs/blurredwallpaper/default.nix
Enhanced the Nix file; actually add the correct references;
=> Enhanceblurred

modules/nordvpn.nix, overlays/default.nix, pkgs/nordvpn/default.nix
Added a new package.
This is sourced from an [open PR at Nixpkgs](https://github.com/NixOS/nixpkgs/pull/220616/files) and shall be replaced once the PR is merged.
=> nordvpn: init at 3.16.3

flake.lock
=> flake-20230714-1: mesa, sway

devshells/failures.nix, flake.lock
=> flake-20230715-1: mangohud, mesa, sway, wlroots

flake.lock
=> flake-20230717-1: mesa, sway, wlroots

flake.lock, pkgs/yuzu-ea-git/default.nix
=> flake-20230718-1: mesa, wlroots

flake.lock, flake.nix, overlays/default.nix, pkgs/yt-dlp-git/default.nix
Adds `yt-dlp_git` package.
The websites it supports change abruptly, this allows people to sooner try the fixes.
=> yt-dlp_git: init

overlays/default.nix, pkgs/luxtorpeda/default.nix, pkgs/luxtorpeda/update.nix, pkgs/luxtorpeda/version.json
1. Add update-script to luxtorpeda;
2. Bump luxtorpeda.
I was totally forgetting to update this one.
=> luxtorpeda: 63 -> 65.1.1; init update-script

pkgs/dr460nized-kde-theme/default.nix
Bumped package;
Theming updates 😊
=> dr460nized-kde-theme: update to unstable-2023-07-29

pkgs/firedragon/src.json
Update `firedragon`!
Regular updates;
=> firedragon: update 116.0.1

pkgs/vulkan-versioned/default.nix, pkgs/vulkan-versioned/latest.json, pkgs/vulkan-versioned/utility-libraries.nix
Add a library we're not gonna use right now.
Once they release a new version of the SDK, we're probably going to use it, and I would rather not leave this lost somewhere in my SSD.
=> vulkanPackages_latest.vulkan-utility-libraries: init at v1.3.261

devshells/builder.nix, devshells/document.nix, devshells/failures.nix, flake.lock, overlays/default.nix, pkgs/input-leap-git/default.nix, shared/recursion-helper.nix
1. Bump our packages;
2. Rebase `input-leap_git`;
3. Change builder's output.
- (1) We do this daily;
- (2) I don't need to reinvent the wheel anymore;
- (3) Better to understand in the CI's dashboard.
=> Bump 20230812-1; input-leap_git: rebase; builder: enhance

pkgs/firedragon/default.nix, pkgs/firedragon/update.nix
Added some CI code.
Because I want to be lazy.
=> firedragon: add updater

overlays/default.nix, pkgs/alacritty-git/default.nix, pkgs/alacritty-git/update.nix, pkgs/alacritty-git/version.json
Add `alacritty_git`.
This version works with our `sway_git`.
=> alacritty_git: init

overlays/default.nix, pkgs/fastfetch/default.nix, pkgs/yyjson/default.nix
1. Bumped `fastfetch`
2. Added `yyjson` (needed for `fastfetch`)
Always stay ahead of versions!
=> yyjson: init at 0.7.0; fastfetch: update 2.0.0

flake.lock
Bump our packages since we do this daily.
=> flake-20230819-2: mesa, yuzu-ea

flake.lock, flake.nix, overlays/default.nix, pkgs/ananicy-cpp-rules/default.nix, pkgs/beautyline-icons/default.nix, pkgs/dr460nized-kde-theme/default.nix, pkgs/nordvpn/default.nix
Added an updater for ananicy-cpp-rules
To make my life easier.
=> ananicy-cpp-rules, beautyline-icons, dr460nized-kde-theme: add updater; nordvpn: update 3.16.5

devshells/failures.nix, flake.lock, pkgs/openmohaa/version.json, pkgs/proton-ge-custom/versions.json
Bump our packages, we do this daily.
=> Bump 20230821-1

devshells/failures.nix, pkgs/openmohaa/default.nix
Add bison and flex to openmohaa
Fixes it.
=> openmohaa: add bison and flex

pkgs/fastfetch/default.nix
Update version 2.0.2.
New features and bugfixes.
=> fastfetch: update to 2.0.2

modules/nixos/mesa-git.nix
1. use sessionVariables instead;
2. remove `LD_LIBRARY_PATH` useless method.
- (1) I was wrong when I reverted this, `sessionVariables` comes before `variables`;
- (2) No use-case.
=> nixos/mesa-git: use sessionVariables instead; remove useless method

overlays/default.nix, pkgs/firefox-nightly/default.nix, pkgs/firefox-nightly/update.nix, pkgs/firefox-nightly/version.json, pkgs/nss-git/default.nix, pkgs/nss-git/version.json
1. Add `nss_git`;
2. Add `firefox_nightly`.
- (1) Required for (2);
- (2) Closes #286.
=> firefox_nightly: init; nss_git: init

devshells/document.nix, modules/nixos/appmenu-gtk3-module.nix, pkgs/mesa-git/default.nix, pkgs/mesa-git/opencl.patch, pkgs/vulkan-versioned/latest.json
- rebases `mesa-git/opencl.patch`;
- revert `vulkanPackages_latest.vulkan-validation-layers` bump.
Fixes issues brought with 113f4b09c1bce4389028e417101a531e316518c3.
=> Fixes 113f4b09c1bce4389028e417101a531e316518c3

pkgs/firefox-nightly/update.nix, pkgs/firefox-nightly/version.json, pkgs/mesa-git/default.nix
1. Add rebased `opencl.patch`;
2. Don't ""bin"" firefox's update-script;
3. Bumps firefox.
- (1) I forgot;
- (2) I broke it;
- (3) Put (2) to work.
=> Fixes 8ad4d368d6e5f6c1a7400f158ba5269f54e870e0

.editorconfig, devshells/document.nix, modules/nixos/default.nix, modules/nixos/duckdns.nix, statix.toml
Port @thiagokokada's module to Chaotic-Nyx.
I will totally use it.
=> nixos/duckdns: init

overlays/default.nix, pkgs/glib-git/default.nix, pkgs/glib-git/version.json, pkgs/glibmm-git/default.nix, pkgs/glibmm-git/version.json, pkgs/telegram-desktop-git/default.nix, pkgs/telegram-desktop-git/version.json, pkgs/tg-owt-git/default.nix, pkgs/tg-owt-git/version.json, pkgs/vkshade-git/default.nix
Adds `telegram-desktop_git` and all the sub-depedencies required for it to run.
Looks like nixpkgs will take some time before bumping it.
=> telegram-desktop_git: init

.github/workflows/build.yml, maintenance/tools/builder/default.nix
In the comments of a successful build, add the amount of entries that were not suitable for building.
I want to know if this number ever increases.
Maybe I should count the pinned and upstreamed ones too?
=> builder: let me know the count of unbuildable in the comment

pkgs/vulkan-versioned/latest.json
Fixes issues introduced in #348 
Small set of changes needed for devs to keep using them.
=> vulkanPackages_latest: fixes

pkgs/firefox-nightly/version.json, pkgs/vulkan-versioned/latest.json
I don't want to fix those today, it's Saturday.
=> Saturday reverts

pkgs/firedragon/src.json, pkgs/firefox-nightly/version.json, pkgs/vulkan-versioned/latest.json
- #356 broke some stuff;
- in #357 I mistakenly reverted "firefox" instead of "firedragon" (Cc @dr460nf1r3);
- in #357 I forgot to reverse validation layers.
Monday I'll fix them all.
=> Saturday reverts 2

pkgs/firedragon/firedragon.nix, pkgs/firedragon/src.json
Fixed the build of `firedragon`;
A patch got deprecated;
=> firedragon: 117.0.1 -> 118.0

flake.nix, overlays/default.nix, pkgs/alacritty-git/default.nix, pkgs/extra-cmake-modules-git/latest.nix, pkgs/gamescope-git/default.nix, pkgs/glib-git/default.nix, pkgs/glibmm-git/default.nix, pkgs/input-leap-git/default.nix, pkgs/kf6coreaddons-git/latest.nix, pkgs/mangohud-git/default.nix, pkgs/mesa-git/default.nix, pkgs/nix-flake-schemas-git/default.nix, pkgs/nss-git/default.nix, pkgs/openmohaa-git/default.nix, pkgs/river-git/default.nix, pkgs/sway-unwrapped-git/default.nix, pkgs/swaylock-plugin-git/default.nix, pkgs/telegram-desktop-git/default.nix, pkgs/tg-owt-git/default.nix, pkgs/vkshade-git/default.nix, pkgs/wayland-git/default.nix, pkgs/wayland-protocols-git/default.nix, pkgs/waynergy-git/default.nix, pkgs/wlroots-git/default.nix, pkgs/yt-dlp-git/default.nix, pkgs/yuzu-ea-git/default.nix, shared/git-override.nix, shared/github-rev-fetcher.nix, shared/gitlab-rev-fetcher.nix
Make `gitOverride` usage simpler.
It was nowhere near my best APIs.
=> gitOverride: refactorate

pkgs/gamescope-git/default.nix
Move `gamescope_git` to `wlroots_git`, with `vulkanPackages_latest`, and `wayland_git`.
=> gamescope_git: make it more prominent to failures

pkgs/alacritty-git/version.json, pkgs/ananicy-cpp-rules/version.json, pkgs/extra-cmake-modules-git/version.json, pkgs/gamescope-git/version.json, pkgs/linux-cachyos/update.nix
I've tested with these, don't want to waste them.
=> Bump 20231015-2

pkgs/linux-cachyos/default.nix, pkgs/mangohud-git/version.json, pkgs/mesa-git/version.json, shared/utils.nix
=> Bump 20231024-2

.github/workflows/needs-cache.yml, maintenance/tools/builder/lib.sh, pkgs/mangohud-git/version.json, pkgs/mesa-git/version.json
Bumps the 32-bit apps.
Blocked to update on CI because of #402
=> Bump 20231030-2 (32bit)

pkgs/mangohud-git/version.json, pkgs/mesa-git/version.json
=> Bump 20231112-2

maintenance/failures.nix, pkgs/mangohud-git/version.json, pkgs/mesa-git/version.json
Needed updating failures, so I also took the packages affected by #402
=> Bump 20231114-2

overlays/default.nix, pkgs/alacritty-git/version.json, pkgs/extra-cmake-modules-git/version.json, pkgs/firefox-nightly/version.json, pkgs/gamescope-git/version.json, pkgs/glib-git/version.json, pkgs/input-leap-git/version.json, pkgs/mesa-git/version.json, pkgs/proton-ge-custom/versions.json, pkgs/sway-unwrapped-git/version.json, pkgs/telegram-desktop-git/version.json, pkgs/vulkan-versioned/latest.json, pkgs/wayland-git/version.json, pkgs/wlroots-git/version.json, pkgs/yt-dlp-git/version.json, pkgs/yuzu-ea-git/version.json
=> Bump 20231122-1

pkgs/linux-cachyos/versions.json
Update CachyOS' ZFS commit
Avoid issues
=> linuxPackages_cachyos.zfs: update

pkgs/mesa-git/version.json, pkgs/sway-unwrapped-git/version.json, pkgs/wlroots-git/version.json
=> Bump 20231125-2

.github/workflows/build.yml, .github/workflows/document.yml, .github/workflows/flakehub-publish-rolling.yml, .github/workflows/full-bump.yml, .github/workflows/needs-cache.yml, .github/workflows/nixpkgs-bump.yml, .github/workflows/pull-request.yml, .github/workflows/single-bump.yml, .github/workflows/wip-build.yml, maintenance/dev-shells/default.nix
1. Allows me to bump individual packages through GH Actions;
2. Allows me to build any branch through GH Actions;
3. Fix a small mistake within full-bump;
4. Bump Nix version.
- (1) Sometimes I need to bump the kernels all alone;
- (2) Sometimes I need to build stuff knowing that half of it will fail.
=> ci: init missing stuff for afk; nix 2.18 -> 2.19

overlays/default.nix, pkgs/qtile-extras-git/default.nix, pkgs/qtile-extras-git/version.json, pkgs/qtile-git/default.nix, pkgs/qtile-git/version.json
1. Add `qtile_git`;
1. Add `qtile-extras_git`;
Drishal asked for them.
=> qtile_git: init with qtile-extras_git

pkgs/firefox-nightly/version.json, pkgs/mesa-git/version.json
Stuff that Immortalis failed to build but are not broken
=> Bump 20240105-2

pkgs/mesa-git/default.nix
Reverts MR 24386
It broke something more critical to building
=> mesa_git: revert MR 24386

overlays/default.nix, pkgs/sdl-git/default.nix, pkgs/sdl-git/version.json
Add `sdl_git` package that builds from the main branch.
Some projects are starting to use SDL3, this should help them.
=> sdl_git: init at 20240109194312-6407e0c

pkgs/river-git/default.nix, pkgs/river-git/version.json
Bumps river_git.
I was waiting for the new wlroots for it to properly build.
=> river_git: 20231117185157-50ccd4c -> 20240113183620-69a51ca

pkgs/scx/common.nix, pkgs/scx/default.nix, pkgs/scx/layered/Cargo.lock, pkgs/scx/rustland/Cargo.lock, pkgs/scx/rusty/Cargo.lock
Bumps scx.
Bleeding-edge repo.
=> scx: 0.1.5 -> 0.1.6

maintenance/failures.x86_64-linux.nix, pkgs/firefox-nightly/version.json, pkgs/mesa-git/version.json, pkgs/nss-git/version.json, pkgs/yuzu-ea-git/default.nix, pkgs/yuzu-ea-git/version.json
=> Bump 20240131-2

flake.lock, flake.nix, overlays/default.nix
Cache some Jovian's packages.
Closes #572 
To make sure you'll download the latest version we cached, I recommend you to use Jovian like this:
```nix
{
description = "...";
inputs = {
nixpkgs.follows = "chaotic/nixpkgs";
jovian.follows = "chaotic/jovian";
chaotic.url = "https://flakehub.com/f/chaotic-cx/nyx/0.1.*.tar.gz";
};
```
=> jovian-chaotic: init

pkgs/firedragon/default.nix, pkgs/firedragon/firedragon.nix, pkgs/firedragon/src.json, pkgs/firedragon/src.nix
Updates `firedragon` to the new rebased version.
We rebased to Floorp and this update brings the new changes.
=> firedragon: 119.0 -> 11.9.0

pkgs/mesa-git/default.nix
=> i915 driver on mesa-git

pkgs/firedragon/src.json
Update the `firedragon` package.
Gib updates!
=> firedragon: 10.9.0 -> 11.10.5

pkgs/applet-window-title/default.nix
=> applet-window-title: 0.3 -> 0.5

pkgs/firedragon/firedragon.nix, pkgs/firedragon/src.json
Update `firedragon`.
Keeping stuff up-to-date.
=> firedragon: 11.10.5 -> 11.11.2

README.md, pkgs/ananicy-cpp-rules/default.nix
1. Updated the installPhase of `ananicy-cpp-rules` to remove LICENSE file too, before installing
2. Updated README docs about using a scx scheduler.
- (1) Why not?
=> Update install phase of ananicy-cpp-rules, update README docs about scx

pkgs/scx/common.nix, pkgs/scx/default.nix, pkgs/scx/lavd/Cargo.lock, pkgs/scx/layered/Cargo.lock, pkgs/scx/rlfifo/Cargo.lock, pkgs/scx/rustland/Cargo.lock, pkgs/scx/rusty/Cargo.lock
Updated to scx to the latest stable version.
Why not?
- Dark chocolate is objectively better :)
=> scx: unstable-20240429-b1bb2a5c5 -> v0.1.10

pkgs/scx/default.nix, pkgs/scx/lavd/default.nix, pkgs/scx/layered/default.nix, pkgs/scx/rlfifo/default.nix, pkgs/scx/rustland/default.nix, pkgs/scx/rusty/default.nix
1. Fix build failure of scx_* binaries. (just like https://github.com/NixOS/nixpkgs/pull/325702)
=> scx: fix build failure

pkgs/blurredwallpaper/default.nix
Bumped package.
Because I can.
=> blurredwallpaper: 3.0.1 -> 3.1.0

pkgs/firedragon/default.nix, pkgs/firedragon/firedragon.nix, pkgs/firedragon/version.json
Bumped package.
Contains the version update from ESR115 -> ESR128 !
=> firedragon: 11.16.0-1 -> 11.17.1-1

overlays/default.nix, pkgs/firedragon/version.json
1. Bumped package
2. Add something very essential I forgot earlier
=> firedragon: 11.17.5-1 -> 11.17.6-1

maintenance/tools/builder/lib.sh, pkgs/alacritty-git/version.json, pkgs/ananicy-cpp-rules/version.json
Minor daily bump of packages that I need. If anyone wants a specific package from https://github.com/chaotic-cx/nyx/pull/905/commits, let me know.
This also fixes `alacritty_git` on main.
=> Minor daily bump 27-10-2024

pkgs/discord-krisp/krisp-patcher.py
Updated patcher including commits https://github.com/sersorrel/sys/commit/d19bd7c27226870cb262175f33fa2af2ba6bb86b & https://github.com/sersorrel/sys/commit/7806b21ce74ef7953c3d38edb0116cc9d0851302 from original patcher
Fixes patching [log](https://pastebin.com/X3dcdaLt)
=> discord-krisp: Update patcher

README.md
Updated to the latest implementation.
=> README: update scx docs

overlays/default.nix, pkgs/owl-git/package.nix
1. Init `owl_git`
- I really wan't this package since nor river or sway actually suits me.
- Do you like roses?
=> owl-wlr: init at unstable-20241209-37efc0c0d

pkgs/zed-editor-git/version.json
=> zed-editor_git: 20250308000257-60b3eb3 -> 20250309161137-6de3ac3

pkgs/scx-git/common.nix, pkgs/scx-git/cscheds.nix, pkgs/scx-git/rustscheds.nix, pkgs/scx-git/update.sh, pkgs/scx-git/version.json
Currently suffers the same bug as https://github.com/NixOS/nixpkgs/pull/388603.
lavd not working.
=> scx_git: b4db5ee -> d25836a

overlays/default.nix, pkgs/openrgb-git/default.nix, pkgs/openrgb-git/version.json
=> openrgb_git: init

modules/nixos/conduwuit.nix, modules/nixos/default.nix
- depends on https://github.com/chaotic-cx/nyx/pull/1023
- rusty!
=> modules/conduwuit: init

pkgs/zed-editor-git/version.json
=> zed-editor_git: 20250408 -> 20250419082642-d88b06a

overlays/default.nix, pkgs/firefox-nightly/default.nix
Just some minor FF nightly things
=> firefox_nightly: minor fixes; sync to nixpkgs

pkgs/proton-ge-custom/versions.json
Bumped GE-Proton to the newest latest version
=> bump GE-Proton to 10-1

pkgs/firefox-nightly/default.nix, pkgs/firefox-nightly/version.json
=> firefox_nightly: remove workarounds

pkgs/zed-editor-git/0002-fix-duplicate-reqwest.patch, pkgs/zed-editor-git/default.nix, pkgs/zed-editor-git/version.json, shared/git-override.nix
=> zed-editor_git: unblock

overlays/default.nix, pkgs/pcsx2-git/default.nix, pkgs/pcsx2-git/version.json
=> pcsx2_git: init at 20250603114440-952c39f

overlays/default.nix
1. Added a new package;
2. Added a new module;
3. Bumped package;
4. Enhanced some CI code.
- (1) This new package is interesting to myself;
- (2) This new module makes it easier to rice my linux;
- (3) Fixes error [log](https://pastebin.com/example);
- (4) Faster build times.
- I've changed something unrelated in X because Y was worse.
=> Is it a typo? cachyos-hardened = ... rc

pkgs/scx-git/cscheds.nix, pkgs/scx-git/rustscheds.nix, pkgs/scx-git/version.json
=> scx_git: d4dd7b1 -> dc7c785

overlays/default.nix
=> scx_git: fix eval
