chaotic-cx/nyx

flake.lock
flake.nix

1. Add `hydraJobs` output to `flake.nix`;
2. Move `gamescope-git` to the new upstream repo address;
3. Bump the `flake.lock`.
- (1) I intend to use this as building points;
- (2) https://twitter.com/Plagman2/status/1641239116196237313;
- (3) Update `mesa-git` and `nixpkgs`.
```console
╰─λ nix eval .#hydraJobs.default.aarch64-linux --apply builtins.attrNames
[ "gamescope-git" "input-leap-git" "libei" "linuxPackages_hdr" "linux_hdr" "mesa-git" "mesa-git-32" "sway-git" "sway-unwrapped-git" "waynergy-git" "wlroots-git" ]
╰─λ nix eval .#hydraJobs.default.aarch64-linux.libei --apply builtins.toString
"/nix/store/bafpjjsj79vq4vnq951l5klzdj6wvqsg-libei-0.4.1"
```

 flake: add hydraJobs output; bump

---

overlays/default.nix

If the recipe uses `override` or `overrideAttrs`, then use `prev`, otherwise use `final`.
To help some users by avoiding infinite recursions.

overlay: use prev for everything that uses override

---

overlays/default.nix
pkgs/libei/default.nix

We can deprecate `libei_0_4` once input-leap moves to it.

libei: 0.4.1 -> 0.5

---

README.md
overlays/default.nix
pkgs/beautyline-icons/default.nix

This package most likely can't be upstreamed due to another package already existing. This one however uses another repository as the source and does not contain Candy icons either.

beautyline-icons: init at unstable-2023-04-02

---

README.md
overlays/default.nix
pkgs/applet-window-appmenu/default.nix
pkgs/applet-window-title/default.nix

While things aren't upstreamed yet, it would be nice to have these available and prebuilt. (yes, I ran `nix fmt .` before pushing)

applet-window-{appmenu,title}: init at {unstable-2023-04-02,0.7.1}

---

README.md
flake.nix
modules/default.nix
modules/gamescope.nix
modules/linux_hdr.nix
modules/mesa-git.nix
pkgs/gamescope-wrapped/default.nix

Add modules to have `gamescope` and `gamescope-sesion` (gamescope that launches steam and takes the entire TTY for it);
The best gaming experience, HDR powered, out-of-the-box.

gamescope-session: init (with HDR support)

---

.gitignore
README.md
overlays/default.nix
pkgs/ananicy-cpp-rules/default.nix

There is no ruleset for `ananicy-cpp`, therefore this provides them. It's explicitly meant for `ananicy-cpp` as rulesets aren't 100% compatible.

ananicy-cpp-rules: init at unstable-2023-03-31

---

flake.lock
pkgs/ananicy-cpp-rules/default.nix
pkgs/applet-window-appmenu/default.nix
pkgs/applet-window-title/default.nix
pkgs/beautyline-icons/default.nix
pkgs/firedragon/default.nix

flake: 20230411-2

---

README.md
overlays/default.nix
pkgs/dr460nized-kde-theme/default.nix

This is pretty much the Sweet KDE theme, tweaked to fit the dr460nized setup best (as seen in Garuda Linux). It depends on `sweet-nova`.

dr460nized-kde-theme: init at unstable-2023-04-02

---

flake.lock
modules/mesa-git.nix
overlays/default.nix
pkgs/mesa-git/default.nix
pkgs/wlroots-git/default.nix

- packages: use underline convention;
- flake-20230415-1: mesa_git, sway_git, wlroots_git;
- mesa_git: use directx-headers_next;
- mesa32_git: use directx-headers32_next;
- wlroots_git: use wayland_next;
- sway_git: use wayland_next;
- directx-headers_next: init at 1.610.0;
- directx-headers32_next: init at 1.610.0;
- wayland_next: init at 1.22.0.

packages: use underline convention; bump mesa_git, sway_git, and wlroots_git

---

.github/workflows/needs-cache.yml

This deletes the preinstalled, unneeded tools to get more space for building (idea from here: https://github.com/easimon/maximize-build-space) Nix packages. I ran into space issues when building derivations on my own flake repo, so this will be a good idea to save us time in the future.

ci: provide more space for nix builds

---

README.md
flake.lock
modules/mesa-git.nix
overlays/default.nix
pkgs/ananicy-cpp-rules/default.nix
pkgs/applet-window-appmenu/default.nix
pkgs/applet-window-title/default.nix
pkgs/beautyline-icons/default.nix
pkgs/dr460nized-kde-theme/default.nix
pkgs/firedragon/default.nix
pkgs/gamescope-git/default.nix
pkgs/input-leap-git/default.nix
pkgs/mesa-git/default.nix
pkgs/wlroots-git/default.nix
shared/utils.nix

Also bumps `mesa_git` version.
Unrelated changes:
- packages: remove new lines;
- nyxUtils: promote to an attrset accessible from `pkgs`;
- packages: make a standard for unstable versions originating from git flakes.

mesa-git: fix for mesa-23 in nixpkgs

---

.github/workflows/needs-cache.yml
.github/workflows/nixpkgs-bump.yml
flake.nix
shared/builder.nix
shared/derivation-recursive-finder.nix
shared/eval.nix

1. Always check cache before building;
2. Cached results go to `cached.txt`;
3. Migrate builder from `packages.default` to `devShells.default`;
4. Add a `devShells.evaluator`;
5. De-duplicate code into `shared/derivation-recursive-finder.nix`.
- (1) According to Cachix docs[1], downloading `narinfo` is enough to prioritize the cache, so we don't need to download stuff from the cache to keep it from being collected;
- (2) These random text files help debugging;
- (3) Isolate our building infrastructure from our final product;
- (4) This TSV[2] can help to identify changes when compared against our main branch;
- (5) QA.
[1]: https://docs.cachix.org/garbage-collection?highlight=narinfo
[2]: https://en.wikipedia.org/wiki/Tab-separated_values
- Now you have to use `nix develop -c …

builder: export through devShells.default and always check cache; devShells.evaluator: init

---

flake.nix
overlays/default.nix
shared/builder.nix
shared/derivation-recursive-finder.nix
shared/utils.nix

I'm backporting these enhancements from #40 to clean up that one.
Flake:
- fix evaluator devShell;
- move derivationRecursiveFinder to nyxUtils;
Builder:
- full derivation's key on warnings;
- don't recurse inside nyxUtils.

builder: some enhancements

---

README.md
modules/appmenu-gtk3-module.nix
modules/default.nix
overlays/default.nix
pkgs/appmenu-gtk3-module/default.nix

Needed to get an appmenu on KDE for a lot of GTK apps like FireDragon, I think.
Stolen from the already existing PR https://github.com/NixOS/nixpkgs/pull/95412, which sadly didn't have much traction lately.

appmenu-gtk3-module: init at 0.7.6

---

README.md
flake.lock
flake.nix
overlays/default.nix
pkgs/yuzu-ea-git/default.nix

This is the smallest set of changes that made the latest yuzu-early-access work for me.
https://github.com/NixOS/nixpkgs/pull/224348 was a way better effort, adding the dependencies to nixpkgs and migrating to Qt6.
Our AUR buddies seem to be building it with LLVM and lto=thin, we could try that in the future.

yuzu-early-access_git: init

---

pkgs/linux-cachyos/default.nix

If I unstand it correctly, we currently use `manual-config.nix` to build the kernel. This would explain why `defconfig` was seemingly not having any impact on the config, as well as why the config was never applied completely. 
https://github.com/NixOS/nixpkgs/blob/a74daa0ec496a1039de74075d4db093764b2a8ec/pkgs/os-specific/linux/kernel/manual-config.nix#L34
This seems to indicate the .config supplied via `configfile` would only be used if `allowImportFromDerivation` is set to true.

linux-cachyos: add allowImportFromDerivation

---

devshells/builder.nix

Will still have "cat" and "mktemp" from coreutils without absolute paths, but I really don't mind it.

builder: use store paths

---

README.md
modules/default.nix
modules/steam-compat-tools.nix
overlays/default.nix
pkgs/luxtorpeda/default.nix
pkgs/proton-ge-custom/default.nix

NOTE: I intend to drop these when they merge into nixpkgs.
This module uses `sessionVariables`, so you have to re-login if you ran a `nixos-rebuild switch`.
Credits to Shawn8901.

modules/steam-compat-tools: init; proton-ge-custom: init at 55; luxtorpeda: init at 63

---

flake.lock

flake.lock: revert nixpkgs to last working mesa revision

---

.circleci/config.yml

I didn't test it, but:
1. It's 70mb smaller;
2. Comes with `experimental-features = nix-command flakes`;
3. Comes with `accept-flake-config = true`.

ci: use nixpkgs/nix-flakes instead of nixos/nix

---

pkgs/linux-cachyos/default.nix

This now uses `linuxManualConfig` instead of `buildLinux` so we can have 100% CachyOS config.

linux-cachyos: 6.3.1, built with linuxManualConfig

---

pkgs/dr460nized-kde-theme/default.nix

We use it to create the home directories files (no home-manager in the flake), therefore this ships the dotfiles.

dr460nized-kde-theme: add skel directory in preparation for garuda flake

---

pkgs/gamescope-git/default.nix

Fixes build missing `benchmark`.

gamescope_git: update buildInputs

---

flake.lock

Daily bump of our `flake.lock`.
Updates `mesa_git`, `sway_git` and `yuzu-ea`.

flake-20230521-1:mesa, sway, yuzu

---

devshells/failures.nix
pkgs/openmohaa/default.nix

Bump openmohaa to latest tag.
Pulls the diff: https://github.com/openmoh/openmohaa/compare/0.50...v0.52.0

openmohaa: 0.50 -> 0.52.0

---

README.md
flake.lock

1. Puts our binary cache's information as a subtopic in "How to use";
2. Changes "extra-substituters" to "substituters;
3. Changes "trusted-public-keys" to "trusted-public-keys;
4. Bumps the `flake.lock`.
- (1) It's more commonsense to add the cache while installing;
- (2) and (3) -- it seems this is the proper way to do inside the `configuration.nix`;
- (4) Brings the packages to their latest version.

bump-20230528-1; README: move cache and update

---

pkgs/beautyline-icons/default.nix

beautyline-icons: update to unstable-2023-06-03

---

README.md
modules/default.nix
modules/nyx-cache.nix
modules/nyx-overlay.nix

Adds the following options:
```nix
{
chaotic.nyx.cache.enable = true;
chaotic.nyx.overlay.enable = true;
chaotic.nyx.overlay.onTopOf = "flake-nixpkgs"; # either this value or "user-pkgs"
}
```
- To have more cache hits;
- To enhance maintainability;
- To allow users to disable our default's module changes entirely.

 modules/nyx-{cache,overlay}: init 

---

README.md
devshells/failures.nix
flake.lock
overlays/default.nix
pkgs/mesa-git/default.nix
pkgs/sway-unwrapped-git/default.nix
pkgs/wlroots-git/default.nix

- Daily builds of our packages;
- Drop `*_next` since they're up-to-date upstream.

 flake-20230604-1: mesa, nixpkgs, sway, wlroots, yuzu-ea 

---

flake.nix
modules/nyx-overlay.nix

Correctly set `callPackage` in each scope.
Fixes the mistakes I've made while fixing my other mistakes.

nyx-overlay: fix wrong definition of callPackage

---

modules/nyx-overlay.nix

Instead of using the flake input, import it, passing the user's config forward.
Fixes https://github.com/chaotic-cx/nyx/issues/142

nyx-overlay: respect user's config.nixpkgs.config

---

.github/workflows/nixpkgs-bump.yml

Use the https://github.com/Chaotic-Temeraire account for committing to the repo via CI.
Having our own bot is for sure nicer than having the GitHub actions do it.
Today gotta be a great day.

CI: use our service account for commiting nixpkgs updates

---

README.md

fixed syntax error in readme example
because people will add broken code if they copy from it lol

Fix syntax error in example

---

pkgs/openmohaa/default.nix

Bump openmohaa.
Repo targets bleeding-edge.

openmohaa: 0.55.1 -> 0.55.2

---

modules/mesa-git.nix

1. Change `environment.sessionVariables` to `environment.variables`;
2. Preload `libglapi` (I'll find a better solution later).
- (1) Chrome was starting without the envvar; 
- (2) Mixing drivers is exploding browser's glxtest (SISEGV at `_glapi_add_dispatch` through `eglCreateContext`).

modules/mesa-git: fixes for browsers

---

README.md
devshells/failures.nix
pkgs/linux-cachyos/versions.nix

Bumps `linux_cachyos`
We like having the latest version of stuff.

linux_cachyos: 6.3.9-> 6.4

---

pkgs/dr460nized-kde-theme/default.nix

1. Removed invalid launchers from the default layout templates
2. Updated revision
3. Added `blurredwallpaper` to buildinputs
1. Some of the default Garuda applications don't exist on NixOS
2. `blurredwallpaper` is strictly required to not have wallpaper glitches

dr460nized-kde-theme: remove invalid launchers; update; add buildinput

---

flake.lock

Bump `mesa_git` once more today.
Includes a fix for Wayland+EGL apps: https://github.com/chaotic-cx/mesa-mirror/commit/71db99e566dddce8ab9af8a42fba33c40238dd51

mesa_git: bump 20230801-2

---

.github/workflows/build.yml

Don't publish our cache if any of the builds failed.
We can always descriptively skip failures with our `devshell/failures.nix`

ci: don't publish if any package fails

---

devshells/document.nix

1. Make code have `overflow: auto`;
2. Make images have `max-width: 100%`.
This fixes responsiveness, and makes it more similar to GitHub's preview.

document: fix responsiveness

---

.gitignore
modules/nixos/mesa-git.nix
pkgs/mesa-git/default.nix
pkgs/mesa-git/test.nix

1. add DM env to mesa-git module;
2. add half-baked virgl-based VM nixosTest to mesa-git;
3. remove upstreamed `"-Dandroid-libbacktrace=disabled"`.
- (1) Related to #260;
- (2) What I used to test (1);
- (3) upstreamed - no longer necessary.

nixos/mesa-git: add DM env; add half-baked virgl-based VM nixosTest

---

modules/nixos/linux_hdr.nix

Re-add the missing `implicit_layer.d/VkLayer_FROG_gamescope_wsi.x86_64.json`.
I lost it when we dropped our gamescope-session module in favor of upstream's.

nixos/linux-hdr: re-add gamescope WSI files

---

pkgs/linux-cachyos/default.nix

1. Add bcachefs support to `linux_cachyos`
Closes #324
Tested in https://github.com/LudovicoPiero/dotfiles/pull/54

linux_cachyos: add bcachefs patch

---

devshells/default.nix
devshells/document.nix
flake.nix
modules/nixos/mesa-git.nix

1. Use `lib.mkMerge` in `nixos/mesa-git`;
2. Allow disabling the fallback specialisation;
3. Re-use `_dev` while making the documentation.
- (1) Fix the issue where the fallback specialisation was not evaluated;
- (2) One might be fearless or have another specialisation doing the same;
- (3) Code de-dup.

 nixos/mesa-git: fix and allow to disable safety specialisation 

---

modules/nixos/hdr.nix

The args/env required for HDR that were applied to `steam-gamescope` are now applied to simply `gamescope`.
In order to use HDR with Gamescope, it just needs to be launched headless, Steam isn't necessary. For instance, `gamescope --hdr-enabled -- legendary launch game` is a valid way to play a game in HDR.

hdr: Move args/env to programs.gamescope

---

modules/nixos/duckdns.nix

1. support IPv6;
2. add `timers.target`.
Just pulling Kokada's work.

nixos/duckdns: IPv6 and timers.target

---

flake.lock
flake.nix

1. Adopt `UbiqueLambda/yafas`;
2. Adopt `nix-systems/default`.
1. To enhance flake's output's readability;
2. To allow overriding supported systems.

flake: adopt yafas

---

flake.nix
maintenance/dev-shells/default.nix
maintenance/dev/default.nix
maintenance/failures.nix
maintenance/schemas/default.nix
maintenance/schemas/packages/inventory.nix
maintenance/tools/builder/default.nix
modules/common/nyx-overlay.nix
overlays/default.nix
shared/recursion-helper.nix
shared/utils.nix

1. Allowed unfreeRedistributable packages to be built on nyx
2. Refactor _dev
Many things are marked as do not build because they have an unfree license. However, in many cases, these unfree licenses still allow us to redistribute built versions of the package.
- Added meta.nyx.bypassLicense

flake: allow unfreeRedistributable builds

---

overlays/default.nix
pkgs/discord-krisp/default.nix
shared/recursion-helper.nix

1. Added discord-krisp as a new package
- (1) Default nixpkgs discord is not compatible with discord's included krisp, because nix changes the hash of the discord executable, breaking a signature check. This can be solved with a binary byte-patch.
- (2) The binary byte-patch needs to happen during the launch, because the library is downloaded by the discord updater, not retrieved from the binaries that we have direct control over.

discord-krisp: init

---

pkgs/telegram-desktop-git/default.nix
pkgs/vulkan-versioned/default.nix
pkgs/vulkan-versioned/fix-pkgconfig.patch
pkgs/vulkan-versioned/latest.json

- Remove one patch;
- Update another patch;
- Skip yet another vulkan-validation-layers while we don't get a new SPIRV tag.
I like to have a release today too, but I'll skip tomorrow, it's Sunday.

Fixes for bump 20231007-1

---

flake.lock
maintenance/tools/bumper/default.nix
maintenance/tools/bumper/lib.sh

1. No longer try to list what inputs' bumped;
2. Properly recognize exit codes.
- (1) It was broken;
- (2) It was broken too.

bumper: fix exit-code mess

---

pkgs/mesa-git/version.json

No failures here, the builder is just breaking with 32-bits stuff.

mesa_git: 20231017143116-b94b784 -> 20231019143500-4752b18

---

maintenance/tools/builder/lib.sh

We already abused too much from these unsupervised pins:

cachix: only keep two revisions

---

overlays/default.nix
shared/core-tier.nix

Adds `x86-64-v3` builds for the following packages:
```
acl, attr, audit, bash, binutils, bison, brotli, bzip2, coreutils, cracklib, cryptsetup,
curl, dash, db, dbus, debugedit, dialog, diffutils, elfutils, expat, file, findutils,
flex, gawk, gcc, gdbm, gettext, glib, glibc, gmp, gnugrep, gnumake, gnused, gnutar,
gnutls, gpgme, gpm, groff, gsasl, guile, gzip, hwdata, iana, icu, inetutils, inih,
iproute2, iptables, iputils, isl, jansson, jfsutils, json_c, kbd, keyutils, kmod, krb5,
ldns, lemon, less, libaio, libarchive, libargon2, libcap, libedit, libelf, libevent,
libffi, libgcc, libgccjit, libgcrypt, libgpg, libgssglue, libidn2, libksba, libmicrohttpd,
libmnl, libmpc, libnetfilter_conntrack, libnfnetlink, libnftnl, libnghttp2, libnl, libnsl,
libpcap, libpipeline, libpsl, libseccomp, …
```

pkgsx86_64_v3-core: init

---

pkgs/gamescope-git/default.nix
pkgs/gamescope-git/use-pkgconfig.patch
pkgs/gamescope-git/version.json
pkgs/glib-git/version.json
pkgs/mesa-git/default.nix
pkgs/telegram-desktop-git/version.json
pkgs/vulkan-versioned/fix-pkgconfig.patch
pkgs/yt-dlp-git/default.nix

Fixes issues from my last bump.

Bump 20231122-2

---

pkgs/mangohud-git/version.json
pkgs/mesa-git/version.json

The 32 bits apps neglected because of #440.

Bump 20231129-2

---

.github/workflows/wip-build.yml

Wrap the commit code in a condition
I've added the input to the workflow but forgot about dealing with its logic.

ci/wip-build: fix input condition

---

modules/home-manager/default.nix
modules/home-manager/nyx-cache.nix
modules/nixos/default.nix
modules/nixos/nyx-cache.nix

Strict the non-extra settings to NixOS only.
Closes #440.

modules: separate nyx-cache

---

pkgs/mesa-git/default.nix
pkgs/mesa-git/version.json

1. Add `all` to `galliumDrivers` *;
2. Add `all` to `vulkanDrivers` *;
3. Replace `enablePatentEncumberedCodecs` with `-D video-codecs=all` *;
4. Add `NVK` rust deps to `packagecache`;
5. Bump to latest commit.
[*]: Only applies to 64-bit right now.
Shining newer stuff.

mesa_git: add NVK, all drivers, and all codecs

---

README.md
maintenance/tools/document/default.nix
modules/nixos/default.nix
modules/nixos/qtile.nix
pkgs/qtile-git/default.nix
pkgs/qtile-git/test.nix

…ns for sched-ext too
1. Add a module for expanding qtile;
2. Add instructions on how to use `qtile_git`;
3. Add tests to try `qtile_git`;
4. Add instructions for sched-ext.
- (1), (2) and (3) to help Drishal;
- (4) It's something harder too.

qtile: add module, instructions and tests

---

overlays/default.nix

Propagate `pkgs.config` when re-importing Nixpkgs inside `makeMicroarch`
- Fixes #514;
- Also includes other `allow*`.
Tested:
- FAILS (as expected): `nix build .#packages.x86_64-linux.pkgsx86_64_v3.discord-krisp`
- SUCCEED: `NIXPKGS_ALLOW_UNFREE=1 nix build --impure .#packages.x86_64-linux.pkgsx86_64_v3.discord-krisp`
- FAILS (as expected): `sudo nixos-rebuild dry-build` with `nixpkgs.config.allowUnfree = false`
- SUCCEED: `sudo nixos-rebuild dry-build` with `nixpkgs.config.allowUnfree = true`
I've added a `nixpkgsExtraConfig` that is not being used, but that can be helpful for debugging issues.

makeMicroarch: propagate pkgs.config

---

pkgs/mesa-git/default.nix

Reverts https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/24386
Breaks building with tons of `error: no xxxx named 'yyyy' in namespace 'std'`.

mesa_git: revert MR 24386 (again)

---

pkgs/libdrm-git/default.nix
pkgs/mesa-git/default.nix

Matches libdrm_git's drvName's length to the OG one.
So I can use it with replaceRuntimeDependencies.

libdrm_git: match drvName with the original

---

maintenance/failures.x86_64-linux.nix
maintenance/tools/builder/lib.sh
pkgs/distrobox-git/default.nix

Remove a patch from Distrobox.
This patch, that was introduced in this nixos-unstable now, was already upstreamed in this version.

rebase: nixpkgs 0.1.578631

---

flake.lock
flake.nix
overlays/default.nix

Adds `conduit_git`, `jujutsu_git`, and `niri_git`.
I was a little worried about adding third-party's flakes, since flakes' inputs don't really scale well, but since we did it for Jovian, let this sink.

third-party: init conduit_git, jujutsu_git & niri_git

---

flake.lock
flake.nix
overlays/default.nix

- Removes `conduit_git`
- Adds `conduwuit_git` from https://github.com/girlbossceo/conduwuit
It's a fork with fixes and “early-access” to upstream's MRs:
https://github.com/girlbossceo/conduwuit/blob/0593dce8a66788c67e52ecb521c878ef2c53e0c4/DIFFERENCES.md

conduit_git: migrate to conduwuit (renames package)

---

pkgs/applet-window-title/default.nix

Updated this package.
This is a KDE 6 fork with a few more features.
Version got reset due to the fork using different versioning.

applet-window-title: 0.7.1 -> 0.3

---

pkgs/blurredwallpaper/default.nix

Includes KDE 6 compatibility.
Updated a package.
KDE 6 release.

blurredwallpaper: 2.0 -> 3.0.0

---

pkgs/mesa-git/default.nix

Applied https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/26165 to mesa_git
Makes VAAPI in Chromium work by running it with eg.
```
google-chrome-stable --use-gl=angle --use-angle=vulkan --enable-accelerated-video-decode --enable-features=Vulkan,VulkanFromANGLE,DefaultANGLEVulkan,VaapiIgnoreDriverChecks,VaapiVideoDecoder,UseMultiPlaneFormatForHardwareVideo
```

mesa_git: Only export one handle for contiguous planes

---

flake.lock
flake.nix

- Switches conduwuit_git remote to [GitHub](https://github.com/girlbossceo/conduwuit) from [GitLab](https://gitlab.com/girlbossceo/conduwuit)
- Conduwuit development is done only on GitHub
- GitLab, git.gay, Codeberg, sr.ht, etc are only mirrors that I manually push to, and have admittedly forgotten to push to for at most a few days
- Our CI only works on GitHub until I can get a GitLab Runner setup (https://github.com/girlbossceo/conduwuit/issues/160)

conduwuit_git: switch remote to github

---

pkgs/linux-cachyos/configfile-raw.nix

Fixed linux-cachyos-lto configuration generation.
Should fix a few problems with out-of-tree modules.

linux-cachyos: fix config generation

---

modules/nixos/scx.nix

Fixed an error in nixos module.
I want to use modified scx packages (`services.scx.package` option), both in systemd service and in `environment.systemPackages`.

scx package in environment should respect settings

---

README.md

I was trying out the cachyos-sched-ext kernel and rebuild script gave me an error that sched-ext patches are now merged with linux-cachyos.
So...
Updated docs to state that `pkgs.linuxPackages_cachyos-sched-ext` is deprecated and `pkgs.linuxPackages_cachyos` should be used instead.

Update README docs: sched-ext merged with cachyos kernel

---

overlays/default.nix

I was trying to build the system for x86_64-v4, and it failed to build on checkphase for `coreutils` and `ltrace`.
So...
Added conditional overlays for v4 systems which disables checkphase for `coreutils` and `ltrace`.

Overlays: Disable checkphase for coreutils and ltrace on v4

---

pkgs/nix-flake-schemas-git/default.nix

This fixes nix-flake-schemas_git package by renaming the source repository.
Why not?

nix-flake-schemas_git: fix source repository URL

---

overlays/default.nix

1. Added a new package;
- (1) This new package is interesting to myself;
- I added `mesa-radeonsi-jupiter` to `jovian-chaotic`, because my steam deck builds it using the flake.

jovian-chaotic: add mesa-radeonsi-jupiter

---

maintenance/failures.x86_64-linux.nix
overlays/default.nix
pkgs/linux-cachyos/all-packages.nix
pkgs/linux-cachyos/llvm-module-overlay.nix
pkgs/linux-cachyos/make.nix

Added an overlay to make kernel modules use clangStdenv for lto kernel, when building.
- (1) Fixes error [log](https://pastebin.com/Aw3GjXZF);
Please check the package names!
I am confused whether to use linuxKernel.packages.linux_cachyos-lto.somePackage

Fix module building for linux-cachyos-lto kernel

---

modules/nixos/qtile.nix

This renames some config options for `nixpkgs` changes.
Fixes the following error when running `nix flake check`:
```
error: The option `services.xserver.displayManager.sessionPackages' does not exist.
```

Rename options for nixpkgs changes upstream

---

modules/nixos/qtile.nix

Correction of code.
- Fixes error ( `services.xserver.displayManager.sessionPackages` has been renamed to `services.displayManager.sessionPackages`)

qtile: correct path

---

flake.lock
flake.nix

Unpins `crane` from flake.nix for conduwuit builds
The TOML mangle bug has been fixed:
https://github.com/girlbossceo/conduwuit/pull/298
https://github.com/ipetkov/crane/issues/527#issuecomment-2067882206

flake(conduwuit): unpin crane as the toml bug has been fixed

---

overlays/default.nix

1. Added back the firefox wrapper. 
- App was working as expected but the .desktop is seemingly not present once installed in the system without it.

firedragon: add back wrapper, without no .desktop

---

pkgs/firedragon/update.nix

1. Fixed the update script
- Curly braces made the bash variable a Nix variable and broke the update process therefore.

firedragon: fix update script (again)

---

modules/nixos/scx.nix

1. Add stricter type checking for `chaotic.scx.scheduler` option 
2. Improved description of `chaotic.scx.enable` option.
3. Cleanup `with lib;` by using `lib.` explicitly
I don't see a reason to not :)

nixos/scx: improve description, add stricter type checking

---

maintenance/tools/linter/default.nix
modules/nixos/hdr.nix
modules/nixos/scx.nix

1. This deprecates and removes `chaotic.hdr.kernelPackages` option.
2. In additon, adds assertion that for HDR feature to work, kernel has to be built with proper support, ie, with AMD_PRIVATE_COLOR.
- (1) Closes https://github.com/chaotic-cx/nyx/issues/630
- Perhaps this change needs to be notified in the news channel.

nixos/hdr: remove hdr.kernelPackages option and assert AMD_PRIVATE_COLOR

---

pkgs/linux-cachyos/0001-Add-extra-version-CachyOS-rc.patch
pkgs/linux-cachyos/default.nix
pkgs/linux-cachyos/kernel.nix
pkgs/linux-cachyos/packages-for.nix
pkgs/linux-cachyos/update.nix
pkgs/linux-cachyos/versions.json

1. Rework update script
2. Now we can run:
```
bash $(nix build --no-link --print-out-paths **.#linuxPackages_cachyos.kernel.updateScript);
```
or
```
bash $(nix build --no-link --print-out-paths **.#linuxPackages_cachyos-rc.kernel.updateScript);
```
to update seperately.

linux-cachyos: revamp update script

---

pkgs/linux-cachyos/update.nix

1. linux cachyos rc update script now updates the rc kernel version patch as well
2. linux-cachyos-rc: 6.10-rc5 -> rc6
- (1) No extra work needed from now on!

linux-cachyos-rc: update updateScript

---

modules/nixos/scx.nix

from lib.mkPackageOptionMD to lib.mkPackageOption
1. Migrated from deparced `lib.mkPackageOptionMD` to `lib.mkPackageOption`
- (1) To get rid of deparced options. 👀 
- I wish this PR IS suiting your PR requirements!

nixos/scx: lib.mkPackageOptionMD -> lib.mkPackageOption

---

modules/nixos/scx.nix

Added an "scx_bpfland" type to the scx module.
(3) Fixes error:
A definition for option chaotic.scx.scheduler' is not of type one of "scx_central", "scx_flatcg", "scx_lavd", "scx_layered", "scx_nest", "scx_pair", "scx_qmap", "scx_rlfifo", "scx_rustland", "scx_rusty", "scx_simple", "scx_userland"'.

Added "scx_bpfland" to the scx module.

---

pkgs/linux-cachyos/default.nix

When building xone with cachyos-lto throws an error and can't build nixos.
This fix the problem with xone and cachyos-lto making nixos buildable again.
A fast workaround is to change hardware.xone.enable to:
```
boot = {
blacklistedKernelModules = [ "xpad" "mt76x2u" ];
extraModulePackages = [ pkgs.linuxPackages_cachyos.xone ];
};
hardware.firmware = [ pkgs.xow_dongle-firmware ];
```

LLVM xone with cachyos-lto

---

pkgs/firedragon/default.nix
shared/utils.nix

1. Fixed building (again)
2. Added a new function to `nyxUtils` to be able to remove multiple patches at once
- Fixes current build failure

firedragon: fix up build; nyxUtils: add removeByNames

---

pkgs/linux-cachyos/default.nix

When building xone with cachyos-lto throws an error and can't build nixos.
This PR is to fix this issue by adding xone as a LLVM Module.
This fix the problem with xone and cachyos-lto builds errors.
A fast workaround is to change `hardware.xone.enable` to:
```
boot = {
blacklistedKernelModules = [ "xpad" "mt76x2u" ];
extraModulePackages = [ pkgs.linuxPackages_cachyos.xone ];
};
hardware.firmware = [ pkgs.xow_dongle-firmware ];
```

FIX: xone build error with cachyos-lto

---

overlays/default.nix
pkgs/lix-git/default.nix
pkgs/lix-git/version.json

Added `lix_git`. That's what I'm currently using and I have to rebuild it very frequently, which takes ages on my machines.
Lix sparked my interest with a few things, so I'm willing to run it unstable 💥 
A few things I'm excited about are particularly speed improvements and subtle QoL improvements such as multi-line log output.

lix_git: init

---

pkgs/mangohud-git/default.nix

Fixed a package that doesn't build with aliases off.
https://github.com/NixOS/nixpkgs/pull/324562
I have aliases off.
I didn't test, I'm assuming it should work now.

mangohud_git: `glxinfo` -> `mesa-demos`

---

overlays/default.nix
pkgs/godot_4-mono/default.nix
pkgs/godot_4-mono/deps.nix
pkgs/godot_4-mono/make-deps.nix
pkgs/godot_4-mono/make-deps.sh

Added `godot_4-mono`, since the package is not available in Nixpkgs yet, nor is the original PR updated. Lets add it until we have a working upstream package.
https://github.com/NixOS/nixpkgs/pull/285941
It is a very relevant package for a friend of mine, and me.

godot4-mono: init at 4.3-stable

---

modules/nixos/scx.nix

modified a module
disables unnecessary info logging into the journal while keeping error logs
nothing pending
no extra

disable info logging of scx (errors still go to journal)

---

modules/nixos/scx.nix

apparently even the info messages coming from StandardError
updating scx service file 
- disabling journal messages for scx service
Nothing to pending
Sorry for not testing it on the first PR

update service file for scx to actually disable journal logs

---

overlays/default.nix
pkgs/ananicy-cpp-rules/default.nix

1. It's packaged in nixpkgs, so we could use an override.
- (1) This reduces the tarball size?
Are automatic update scripts affected by this? Let me know if I have to change something.

ananicy_cpp-rules -> ananicy-rules-cachyos_git: move to gitOverride

---

pkgs/godot_4-mono/deps.nix

Fixes the build.
- Was broken due to Nuget deps, how ever.
- Fixes #903

godot4_mono: fix build

---

pkgs/nordvpn/default.nix

5. a minor fix for an existing derivation, the nordvpn debian repository dropped the 3.15 versions
- (1) This package is interesting to myself;
- I do like chocolate cake.

fix(nordvpn): fix 404 curl error by updating nordvpn version and repo

---

modules/nixos/default.nix
modules/nixos/owl-wlr.nix

1. `owl-wlr` inits as module! available at `chaotic.owl-wlr.enable = true;`.
- (🏆) To make `owl-wlr`  even more accessible! 
- You see, one loves the sunset when one is so sad. (c) Antuan De Sent Exupery, Little Prince

owl-wlr: module init

---

README.md

According to the notes:
> ## BREAKING CHANGE
> To match the expected behavior of a flake, any non-derivation (e.g., `linuxPackages_cachyos`, `scx_git`, `vulkanPackages_latest`) now lives in `legacyPackage` instead of `packages`.
> To help, some aliases were added: `scx-full_git`, `linux_cachyos{,-hardened,-server}` (kernel only without modules).
> This won't affect users with our `homeManagerModules.default`, which will be able to use `pkgs.linuxPackages_cachyos` as usual.
> 
See #949. Make installation guide more explicit.
Close #949

docs(readme): make chaotic-kernel installation guide more explicit

---

modules/common/nyx-overlay.nix

This PR fixes the overlay, so that binary caches work on NixOS 24.11.
It seems that using `pkgs.stdenv.hostPlatform` (if `pkgs` is from `nixos-24.11`) when importing `inputs.nixpkgs` (`nixpkgs-unstable`) causes the output hashes to diverge. This PR makes sure that we always use `stdenv.hostPlatform` from the Flake `nixpkgs` when using the Flake `nixpkgs` and not cross-compiling.
I tested this on my system and it fixed the output hashes mismatching and thus fixed the binary cache.
The "Why am I building a kernel?" section was really helpful while debugging this. Thanks!

Fix overlay on NixOS 24.11

---

README.md
modules/common/nyx-registry.nix
modules/home-manager/default.nix
modules/nixos/default.nix

1. Adds a module for users to use chaotic easily through Nix tooling;
2. Document usage with stable channels.
- (1) Allows usage like `nix run chaotic#gamescope_git`;
- (2) Plenty of stable users are showing up in chat.

Registry and stable channels

---

modules/nixos/duckdns.nix

Closes https://github.com/chaotic-cx/nyx/issues/980

nixos/duckdns: remove non existing option reference

---

overlays/default.nix

This makes it so we also cache zed-editor-fhs_git.
Followup of https://github.com/NixOS/nixpkgs/pull/387808

zed-editor-fhs_git: init alias to zed-editor_git.fhs

---

pkgs/scx-git/version.json

1. scx_git bumped to 8e33fa9
- sometimes cat's sneeze is just a way to reminder you about them

scx_git: d25836a -> 8e33fa9

---

pkgs/linux-cachyos/prepare.nix

Fixed cachyos bore scheduler patch not being included.

linux_cachyos: fix enabling bore scheduler

---

pkgs/zed-editor-git/default.nix

Opening Zed showed a generic Wayland icon, due to the mismatching app_id and .desktop name. This change should fix it.
See [the official flake](https://github.com/zed-industries/zed/blob/main/flake.nix).
(The icon and the app name aren't changed in this PR.) 
Untested.

zed-editor_git: fix icon

---

pkgs/firedragon/default.nix

See https://github.com/NixOS/nixpkgs/issues/418473
1. Disabled LTO for Firedragon as you get an upstream Floorp/ESR128 bug.
- (1) Might fix this issue: https://github.com/NixOS/nixpkgs/issues/418473 I think
- (2) Speeds up build times and reduces amount of needed memory

firedragon: disable LTO

---

modules/nixos/default.nix
modules/nixos/nyx-home-check.nix

Added a new module.
In the case a user has chosen to have both `.default` options from the home-manager and NixOS modules in this flake, checks if user is using home-manager, and if home-manager.useGlobalPkgs is used. In circumstances where it is, prevent the use of the overlay since this would cause a warning, potentially in future cause an error.
`nix fmt` was then used.
For people who don't want to do this, but are in the same situation regardless, a `chaotic.nyx.overlay.enable = false;` also suffices, but here we are, thus I don't know if it's ultimately necessary, but here we are.

modules: handle home-manager.useGlobalPkgs with a new module

---

pkgs/mwc-git/package.nix

Added mainProgram to mwc-git package
- Fixes
```
$ nix run github:chaotic-cx/nyx/nyxpkgs-unstable#mwc_git
error: unable to execute '/nix/store/qb98fshyszw70iwsyxva27wywg2if27j-mwc-wlr-unstable-20250316235640-33b4968/bin/mwc-wlr': No such file or directory
```

mwc-git: set mainProgram since package and binary names differ

---

modules/nixos/default.nix
modules/nixos/nyx-home-check.nix

Added a new module.
In the case a user has chosen to have both `.default` options from the home-manager and NixOS modules in this flake, checks if user is using home-manager, and if home-manager.useGlobalPkgs is used. In circumstances where it is, prevent the use of the overlay since this would cause a warning, potentially in future cause an error.
This time unlike last time, we introspect to see if chaotic.nyx.overlay exists to be changed.
`nix fmt` was then used.
For people who don't want to do this, but are in the same situation regardless, a `chaotic.nyx.overlay.enable = false;` also suffices, but here we are, thus I don't know if it's ultimately necessary, but here we are.

modules: handle home-manager.useGlobalPkgs with a new module (attempt 2)

---

pkgs/mesa-git/default.nix

https://www.phoronix.com/news/Mesa-Vulkan-AMD-Anti-Lag
The input lag is definitely why I miss all the time with hitscan characters in Marvel Rivals.
Untested.

mesa-git: enable anti-lag layer

---

overlays/default.nix
pkgs/linux-cachyos/default.nix

1. Enables thin LLVM+LTO in `linux_cachyos`;
2. Introduces `linux_cachyos-gcc` as a flavor permanently built with GCC (and without LTO).
Following changes from CachyOS.

linux_cachyos: adopt thin LTO in mainline
